# @generated by usage-cli from cambridge-reader-scraper.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &> /dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in cambridge-reader-scraper." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_cambridge_reader_scraper 'name "Cambridge Reader Scraper"
bin cambridge-reader-scraper
about "Rebuild Cambridge Reader books into PDFs"
flag "-h --help" help="show CLI help" global=#true
flag --userdata help="path to the Cambridge Reader userdata root" global=#true {
    arg <path>
}
flag --app-name help="override the app name used for default userdata discovery" global=#true {
    arg <name>
}
flag --isbn help="limit work to one or more ISBN values" var=#true global=#true {
    arg <isbn>
}
flag --outdir help="output directory for generated PDFs" global=#true {
    arg <path>
}
flag --workdir help="temporary extraction directory" global=#true {
    arg <path>
}
flag --browser help="path to a Playwright Chromium executable" global=#true {
    arg <path>
}
flag --page-timeout-ms help="page navigation timeout in milliseconds" global=#true {
    arg <ms>
}
flag --max-pages help="render only the first N pages of each book" global=#true {
    arg <count>
}
flag --concurrency help="number of books to process in parallel" global=#true {
    arg <count>
}
flag --keep-extracted help="keep extracted book files after rendering" global=#true
flag --no-tui help="disable the interactive selection and progress UI" global=#true
cmd reconstruct help="rebuild selected books into PDFs" {
    alias pdf
}
cmd inspect help="list detected Cambridge Reader book blobs"
cmd completion help="print a shell completion script" {
    arg <shell> {
        choices bash zsh fish powershell xonsh
    }
}
cmd help help="show CLI help"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_cambridge_reader_scraper.spec"
echo $_usage_spec_cambridge_reader_scraper > "$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc cambridge-reader-scraper -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc cambridge-reader-scraper -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
