complete -c cambridge-reader-scraper -f
complete -c cambridge-reader-scraper -n "not __fish_seen_subcommand_from reconstruct pdf inspect completion help" -a "reconstruct" -d "rebuild selected books into PDFs"
complete -c cambridge-reader-scraper -n "not __fish_seen_subcommand_from reconstruct pdf inspect completion help" -a "pdf" -d "alias for reconstruct"
complete -c cambridge-reader-scraper -n "not __fish_seen_subcommand_from reconstruct pdf inspect completion help" -a "inspect" -d "list detected Cambridge Reader book blobs"
complete -c cambridge-reader-scraper -n "not __fish_seen_subcommand_from reconstruct pdf inspect completion help" -a "completion" -d "print a shell completion script"
complete -c cambridge-reader-scraper -n "not __fish_seen_subcommand_from reconstruct pdf inspect completion help" -a "help" -d "show CLI help"
complete -c cambridge-reader-scraper -l userdata -r -d "path to the Cambridge Reader userdata root"
complete -c cambridge-reader-scraper -l app-name -r -d "override the app name used for default userdata discovery"
complete -c cambridge-reader-scraper -l isbn -r -d "limit work to one or more ISBN values"
complete -c cambridge-reader-scraper -l outdir -r -d "output directory for generated PDFs"
complete -c cambridge-reader-scraper -l workdir -r -d "temporary extraction directory"
complete -c cambridge-reader-scraper -l browser -r -d "path to a Playwright Chromium executable"
complete -c cambridge-reader-scraper -l page-timeout-ms -r -d "page navigation timeout in milliseconds"
complete -c cambridge-reader-scraper -l max-pages -r -d "render only the first N pages of each book"
complete -c cambridge-reader-scraper -l concurrency -r -d "number of books to process in parallel"
complete -c cambridge-reader-scraper -l keep-extracted -d "keep extracted book files after rendering"
complete -c cambridge-reader-scraper -l no-tui -d "disable the interactive selection and progress UI"
complete -c cambridge-reader-scraper -l help -d "show CLI help"
complete -c cambridge-reader-scraper -n "__fish_seen_subcommand_from completion" -a "bash" -d "bash completion script"
complete -c cambridge-reader-scraper -n "__fish_seen_subcommand_from completion" -a "zsh" -d "zsh completion script"
complete -c cambridge-reader-scraper -n "__fish_seen_subcommand_from completion" -a "fish" -d "fish completion script"
complete -c cambridge-reader-scraper -n "__fish_seen_subcommand_from completion" -a "powershell" -d "powershell completion script"
complete -c cambridge-reader-scraper -n "__fish_seen_subcommand_from completion" -a "xonsh" -d "xonsh completion script"
