# @generated by usage-cli from cambridge-reader-scraper.usage.kdl
_cambridge_reader_scraper() {
    if ! type -p usage &> /dev/null; then
        echo >&2
        echo "Error: usage CLI not found. This is required for completions to work in cambridge-reader-scraper." >&2
        echo "See https://usage.jdx.dev for more information." >&2
        return 1
    fi

	local cur prev words cword was_split comp_args
    _comp_initialize -n : -- "$@" || return
    local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_cambridge_reader_scraper.spec"
    cat >| "$spec_file" <<'__USAGE_EOF__'
name "Cambridge Reader Scraper"
bin cambridge-reader-scraper
about "Rebuild Cambridge Reader books into PDFs"
flag "-h --help" help="show CLI help" global=#true
flag --userdata help="path to the Cambridge Reader userdata root" global=#true {
    arg <path>
}
flag --app-name help="override the app name used for default userdata discovery" global=#true {
    arg <name>
}
flag --isbn help="limit work to one or more ISBN values" var=#true global=#true {
    arg <isbn>
}
flag --outdir help="output directory for generated PDFs" global=#true {
    arg <path>
}
flag --workdir help="temporary extraction directory" global=#true {
    arg <path>
}
flag --browser help="path to a Playwright Chromium executable" global=#true {
    arg <path>
}
flag --page-timeout-ms help="page navigation timeout in milliseconds" global=#true {
    arg <ms>
}
flag --max-pages help="render only the first N pages of each book" global=#true {
    arg <count>
}
flag --concurrency help="number of books to process in parallel" global=#true {
    arg <count>
}
flag --keep-extracted help="keep extracted book files after rendering" global=#true
flag --no-tui help="disable the interactive selection and progress UI" global=#true
cmd reconstruct help="rebuild selected books into PDFs" {
    alias pdf
}
cmd inspect help="list detected Cambridge Reader book blobs"
cmd completion help="print a shell completion script" {
    arg <shell> {
        choices bash zsh fish powershell xonsh
    }
}
cmd help help="show CLI help"
__USAGE_EOF__
    # shellcheck disable=SC2207
	_comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
	_comp_ltrim_colon_completions "$cur"
    # shellcheck disable=SC2181
    if [[ $? -ne 0 ]]; then
        unset COMPREPLY
    fi
    return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
    shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _cambridge_reader_scraper cambridge-reader-scraper
else
    shopt -u hostcomplete && complete -o nospace -o bashdefault -F _cambridge_reader_scraper cambridge-reader-scraper
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
