# @generated by usage-cli from cambridge-reader-scraper.usage.kdl

if (-not (Get-Command 'usage' -ErrorAction SilentlyContinue)) {
    Write-Warning "Error: usage CLI not found. This is required for completions to work in cambridge-reader-scraper."
    Write-Warning "See https://usage.jdx.dev for more information."
    return
}

Register-ArgumentCompleter -Native -CommandName 'cambridge-reader-scraper' -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $tmpDir = if ($env:TEMP) { $env:TEMP } else { [System.IO.Path]::GetTempPath() }
    $specFile = Join-Path $tmpDir "usage__usage_spec_cambridge_reader_scraper.kdl"

    'name "Cambridge Reader Scraper"
bin cambridge-reader-scraper
about "Rebuild Cambridge Reader books into PDFs"
flag "-h --help" help="show CLI help" global=#true
flag --userdata help="path to the Cambridge Reader userdata root" global=#true {
    arg <path>
}
flag --app-name help="override the app name used for default userdata discovery" global=#true {
    arg <name>
}
flag --isbn help="limit work to one or more ISBN values" var=#true global=#true {
    arg <isbn>
}
flag --outdir help="output directory for generated PDFs" global=#true {
    arg <path>
}
flag --workdir help="temporary extraction directory" global=#true {
    arg <path>
}
flag --browser help="path to a Playwright Chromium executable" global=#true {
    arg <path>
}
flag --page-timeout-ms help="page navigation timeout in milliseconds" global=#true {
    arg <ms>
}
flag --max-pages help="render only the first N pages of each book" global=#true {
    arg <count>
}
flag --concurrency help="number of books to process in parallel" global=#true {
    arg <count>
}
flag --keep-extracted help="keep extracted book files after rendering" global=#true
flag --no-tui help="disable the interactive selection and progress UI" global=#true
cmd reconstruct help="rebuild selected books into PDFs" {
    alias pdf
}
cmd inspect help="list detected Cambridge Reader book blobs"
cmd completion help="print a shell completion script" {
    arg <shell> {
        choices bash zsh fish powershell xonsh
    }
}
cmd help help="show CLI help"
' | Out-File -FilePath $specFile -Encoding utf8

    $words = $commandAst.CommandElements | ForEach-Object { $_.ToString() }
    if ($words.Count -lt 1) {
        $words = @('cambridge-reader-scraper')
    }

    $completions = & 'usage' complete-word --shell powershell -f "$specFile" -- @words $wordToComplete 2>$null

    if ($completions) {
        $completions | ForEach-Object {
            $parts = $_ -split "`t", 2
            $completion = $parts[0]
            $description = if ($parts.Count -gt 1) { $parts[1] } else { '' }

            [System.Management.Automation.CompletionResult]::new(
                $completion,
                $completion,
                'ParameterValue',
                $description
            )
        }
    }
}
